### ISSUE TITLE
Allow pools of size 1

### ISSUE THREAD

**Issue by hobofan** [celluloid/celluloid-pool#1]
Is there any reason that pools have a minimum size of 2? That limit also doesn't seem to be strictly enforced after initialization.

Of course if you are always going to have only 1 worker a pool doesn't make much sense, but I can imagine a lot of scenarios (and I am currently trying to use it in one), where you would start out with a pool size of 1 and scale it up later.

**Comment by tarcieri** [comment]
The existing Lovecraftian monstrosity of an implementation breaks if the pool size is one.

The code that lets you dynamically resize pools didn't account for this.

**Comment by e2** [comment]
I've implemented/fixed this, but the changes are waiting for other merges.

The safe solution is to have a "grow"+"shrink" api for resizing - and only using that (even during shutdown, it's about shrinking the pool one by one).

I even went to far as to "start with 0" and "grow" on demand (when worker method is called). I'm sure some people may want to "lock" a given number of threads at initialization - but this should be a separate method, really.

**Comment by digitalextremist** [comment]
@e2, you mean in changes not covered by #2 right? Because I still see an exception raised there `< 2`

**Comment by e2** [comment]
@digitalextremist - yes, it's not publicly available because it needs more prior "groundwork" merged into Celluloid first (e.g. changes to shutdown logic).

**Comment by digitalextremist** [comment]
@hobofan this is now available on the `0.17.0-prerelease` branch of `Celluloid`

**Comment by hobofan** [comment]
@digitalextremist Thank you! :)

**Comment by digitalextremist** [comment]
@hobofan no problem, if you plan to use it, hold while I also add #4
